apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ecoganpati-store-build
  labels:
    app: ecoganpati-store
spec:
  output:
    to:
      kind: ImageStreamTag
      name: ecoganpati-store:latest
  source:
    type: Git
    git:
      uri: https://github.com/your-repo/ecoganpati-store.git
      ref: main
    contextDir: /
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
  - type: ConfigChange
  - type: GitHub
    github:
      secret: github-webhook-secret
  - type: ImageChange
    imageChange: {}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ecoganpati-store
  labels:
    app: ecoganpati-store
spec:
  lookupPolicy:
    local: false
