apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoganpati-store
  labels:
    app: ecoganpati-store
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecoganpati-store
  template:
    metadata:
      labels:
        app: ecoganpati-store
        version: v1
    spec:
      containers:
      - name: ecoganpati-store
        image: gketan91/ecoganpati_spring_boot_openshift
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
          - mountPath: /app/data
            name: ecoganpati-storage
          - mountPath: /tmp
            name: tmp-storage
      volumes:
        - name: ecoganpati-storage
          persistentVolumeClaim:
            claimName: ecoganpati-pvc
        - name: tmp-storage
          emptyDir: { }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecoganpati-config
data:
  application.yml: |
    server:
      port: 8080
    spring:
      application:
        name: ecoganpati-store
    management:
      endpoints:
        web:
          exposure:
            include: health,info
      endpoint:
        health:
          show-details: always
    logging:
      level:
        com.ecoganpati: INFO
