apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ecoganpati-sc
provisioner: kubernetes.io/aws-ebs # change according to your cloud (eg: aws-ebs, gce-pd, openshift.io/aws-ebs, or local)
parameters:
  type: gp2                      # example for AWS EBS gp2 volume
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
